// ISO 3166-1 alpha-3 → { alpha2, name }
const COUNTRY_MAP: Record<string, { alpha2: string; name: string }> = {
  afghanistan: { alpha2: "AF", name: "Afghanistan" },
  alb: { alpha2: "AL", name: "Albania" },
  dza: { alpha2: "DZ", name: "Algeria" },
  ago: { alpha2: "AO", name: "Angola" },
  arg: { alpha2: "AR", name: "Argentina" },
  aus: { alpha2: "AU", name: "Australia" },
  aut: { alpha2: "AT", name: "Austria" },
  aze: { alpha2: "AZ", name: "Azerbaijan" },
  bhs: { alpha2: "BS", name: "Bahamas" },
  bhr: { alpha2: "BH", name: "Bahrain" },
  bgd: { alpha2: "BD", name: "Bangladesh" },
  blr: { alpha2: "BY", name: "Belarus" },
  bel: { alpha2: "BE", name: "Belgium" },
  blz: { alpha2: "BZ", name: "Belize" },
  ben: { alpha2: "BJ", name: "Benin" },
  bmu: { alpha2: "BM", name: "Bermuda" },
  btn: { alpha2: "BT", name: "Bhutan" },
  bol: { alpha2: "BO", name: "Bolivia" },
  bih: { alpha2: "BA", name: "Bosnia and Herzegovina" },
  bwa: { alpha2: "BW", name: "Botswana" },
  bra: { alpha2: "BR", name: "Brazil" },
  brn: { alpha2: "BN", name: "Brunei" },
  bgr: { alpha2: "BG", name: "Bulgaria" },
  bfa: { alpha2: "BF", name: "Burkina Faso" },
  bdi: { alpha2: "BI", name: "Burundi" },
  khm: { alpha2: "KH", name: "Cambodia" },
  cmr: { alpha2: "CM", name: "Cameroon" },
  can: { alpha2: "CA", name: "Canada" },
  chl: { alpha2: "CL", name: "Chile" },
  chn: { alpha2: "CN", name: "China" },
  col: { alpha2: "CO", name: "Colombia" },
  cod: { alpha2: "CD", name: "Congo (DRC)" },
  cog: { alpha2: "CG", name: "Congo" },
  cri: { alpha2: "CR", name: "Costa Rica" },
  civ: { alpha2: "CI", name: "Côte d'Ivoire" },
  hrv: { alpha2: "HR", name: "Croatia" },
  cub: { alpha2: "CU", name: "Cuba" },
  cyp: { alpha2: "CY", name: "Cyprus" },
  cze: { alpha2: "CZ", name: "Czechia" },
  dnk: { alpha2: "DK", name: "Denmark" },
  dji: { alpha2: "DJ", name: "Djibouti" },
  dom: { alpha2: "DO", name: "Dominican Republic" },
  ecu: { alpha2: "EC", name: "Ecuador" },
  egy: { alpha2: "EG", name: "Egypt" },
  slv: { alpha2: "SV", name: "El Salvador" },
  eng: { alpha2: "GB", name: "England" },
  est: { alpha2: "EE", name: "Estonia" },
  eth: { alpha2: "ET", name: "Ethiopia" },
  fji: { alpha2: "FJ", name: "Fiji" },
  fin: { alpha2: "FI", name: "Finland" },
  fra: { alpha2: "FR", name: "France" },
  gab: { alpha2: "GA", name: "Gabon" },
  gmb: { alpha2: "GM", name: "Gambia" },
  geo: { alpha2: "GE", name: "Georgia" },
  deu: { alpha2: "DE", name: "Germany" },
  gha: { alpha2: "GH", name: "Ghana" },
  gbr: { alpha2: "GB", name: "United Kingdom" },
  grc: { alpha2: "GR", name: "Greece" },
  gtm: { alpha2: "GT", name: "Guatemala" },
  gin: { alpha2: "GN", name: "Guinea" },
  guy: { alpha2: "GY", name: "Guyana" },
  hti: { alpha2: "HT", name: "Haiti" },
  hnd: { alpha2: "HN", name: "Honduras" },
  hkg: { alpha2: "HK", name: "Hong Kong" },
  hun: { alpha2: "HU", name: "Hungary" },
  isl: { alpha2: "IS", name: "Iceland" },
  ind: { alpha2: "IN", name: "India" },
  idn: { alpha2: "ID", name: "Indonesia" },
  irn: { alpha2: "IR", name: "Iran" },
  irq: { alpha2: "IQ", name: "Iraq" },
  irl: { alpha2: "IE", name: "Ireland" },
  isr: { alpha2: "IL", name: "Israel" },
  ita: { alpha2: "IT", name: "Italy" },
  jam: { alpha2: "JM", name: "Jamaica" },
  jpn: { alpha2: "JP", name: "Japan" },
  jor: { alpha2: "JO", name: "Jordan" },
  kaz: { alpha2: "KZ", name: "Kazakhstan" },
  ken: { alpha2: "KE", name: "Kenya" },
  kor: { alpha2: "KR", name: "South Korea" },
  kwt: { alpha2: "KW", name: "Kuwait" },
  kgz: { alpha2: "KG", name: "Kyrgyzstan" },
  lao: { alpha2: "LA", name: "Laos" },
  lva: { alpha2: "LV", name: "Latvia" },
  lbn: { alpha2: "LB", name: "Lebanon" },
  lso: { alpha2: "LS", name: "Lesotho" },
  lby: { alpha2: "LY", name: "Libya" },
  ltu: { alpha2: "LT", name: "Lithuania" },
  lux: { alpha2: "LU", name: "Luxembourg" },
  mac: { alpha2: "MO", name: "Macau" },
  mdg: { alpha2: "MG", name: "Madagascar" },
  mwi: { alpha2: "MW", name: "Malawi" },
  mys: { alpha2: "MY", name: "Malaysia" },
  mli: { alpha2: "ML", name: "Mali" },
  mlt: { alpha2: "MT", name: "Malta" },
  mrt: { alpha2: "MR", name: "Mauritania" },
  mex: { alpha2: "MX", name: "Mexico" },
  mda: { alpha2: "MD", name: "Moldova" },
  mco: { alpha2: "MC", name: "Monaco" },
  mng: { alpha2: "MN", name: "Mongolia" },
  mne: { alpha2: "ME", name: "Montenegro" },
  mar: { alpha2: "MA", name: "Morocco" },
  moz: { alpha2: "MZ", name: "Mozambique" },
  mmr: { alpha2: "MM", name: "Myanmar" },
  nam: { alpha2: "NA", name: "Namibia" },
  npl: { alpha2: "NP", name: "Nepal" },
  nld: { alpha2: "NL", name: "Netherlands" },
  nzl: { alpha2: "NZ", name: "New Zealand" },
  nic: { alpha2: "NI", name: "Nicaragua" },
  ner: { alpha2: "NE", name: "Niger" },
  nga: { alpha2: "NG", name: "Nigeria" },
  nmk: { alpha2: "MK", name: "North Macedonia" },
  nor: { alpha2: "NO", name: "Norway" },
  omn: { alpha2: "OM", name: "Oman" },
  pak: { alpha2: "PK", name: "Pakistan" },
  pan: { alpha2: "PA", name: "Panama" },
  png: { alpha2: "PG", name: "Papua New Guinea" },
  pry: { alpha2: "PY", name: "Paraguay" },
  per: { alpha2: "PE", name: "Peru" },
  phl: { alpha2: "PH", name: "Philippines" },
  pol: { alpha2: "PL", name: "Poland" },
  prt: { alpha2: "PT", name: "Portugal" },
  pri: { alpha2: "PR", name: "Puerto Rico" },
  qat: { alpha2: "QA", name: "Qatar" },
  rou: { alpha2: "RO", name: "Romania" },
  rus: { alpha2: "RU", name: "Russia" },
  rwa: { alpha2: "RW", name: "Rwanda" },
  sau: { alpha2: "SA", name: "Saudi Arabia" },
  sen: { alpha2: "SN", name: "Senegal" },
  srb: { alpha2: "RS", name: "Serbia" },
  sgp: { alpha2: "SG", name: "Singapore" },
  svk: { alpha2: "SK", name: "Slovakia" },
  svn: { alpha2: "SI", name: "Slovenia" },
  som: { alpha2: "SO", name: "Somalia" },
  zaf: { alpha2: "ZA", name: "South Africa" },
  esp: { alpha2: "ES", name: "Spain" },
  lka: { alpha2: "LK", name: "Sri Lanka" },
  sdn: { alpha2: "SD", name: "Sudan" },
  sur: { alpha2: "SR", name: "Suriname" },
  swz: { alpha2: "SZ", name: "Eswatini" },
  swe: { alpha2: "SE", name: "Sweden" },
  che: { alpha2: "CH", name: "Switzerland" },
  syr: { alpha2: "SY", name: "Syria" },
  twn: { alpha2: "TW", name: "Taiwan" },
  tjk: { alpha2: "TJ", name: "Tajikistan" },
  tza: { alpha2: "TZ", name: "Tanzania" },
  tha: { alpha2: "TH", name: "Thailand" },
  tls: { alpha2: "TL", name: "Timor-Leste" },
  togo: { alpha2: "TG", name: "Togo" },
  tun: { alpha2: "TN", name: "Tunisia" },
  tur: { alpha2: "TR", name: "Turkey" },
  tkm: { alpha2: "TM", name: "Turkmenistan" },
  uga: { alpha2: "UG", name: "Uganda" },
  ukr: { alpha2: "UA", name: "Ukraine" },
  are: { alpha2: "AE", name: "United Arab Emirates" },
  usa: { alpha2: "US", name: "United States" },
  ury: { alpha2: "UY", name: "Uruguay" },
  uzb: { alpha2: "UZ", name: "Uzbekistan" },
  ven: { alpha2: "VE", name: "Venezuela" },
  vnm: { alpha2: "VN", name: "Vietnam" },
  yem: { alpha2: "YE", name: "Yemen" },
  zmb: { alpha2: "ZM", name: "Zambia" },
  zwe: { alpha2: "ZW", name: "Zimbabwe" },
}

// Reverse map: alpha-2 → alpha-3 for common codes
const ALPHA2_TO_ALPHA3: Record<string, string> = {}
for (const [alpha3, { alpha2 }] of Object.entries(COUNTRY_MAP)) {
  if (!ALPHA2_TO_ALPHA3[alpha2]) {
    ALPHA2_TO_ALPHA3[alpha2] = alpha3
  }
}

/** Convert a 3-letter ISO country code to a 2-letter code. Returns the input if already 2 letters. */
export function countryAlpha3ToAlpha2(code: string): string {
  const normalized = code.toLowerCase()
  if (normalized.length === 2) return normalized.toUpperCase()
  return COUNTRY_MAP[normalized]?.alpha2 ?? normalized.toUpperCase()
}

/** Get a human-readable country name from an ISO alpha-3 code. */
export function countryName(code: string): string {
  const normalized = code.toLowerCase()
  if (normalized.length === 2) {
    // Try reverse lookup
    const alpha3 = ALPHA2_TO_ALPHA3[normalized.toUpperCase()]
    if (alpha3) return COUNTRY_MAP[alpha3].name
    return normalized.toUpperCase()
  }
  return COUNTRY_MAP[normalized]?.name ?? normalized.toUpperCase()
}
